### PR TITLE
Add environment vars to change module urls

### PR DESCRIPTION
**Pull request by maximiliansoelch**
### Motivation and Context

Kubernetes does not like `_` in the urls.

### Description

Add option to customize the module urls via an environment variable.

### CODE REVIEW

**Comment by FelixTJDietrich** [comment]
@pal03377 wasn't this already possible by adjusting the `.ini` file? E.g. `modules.docker.ini` do we need to do it over the environment?

If this is necessary, then the code LGTM but I'm a bit unsure

**Comment by pal03377** [comment]
Alternative solution: #151

**Comment by pal03377** [comment]
Closing this in favor of #151. If #151 does not solve the underlying problem, feel free to re-open :)

**Comment by maximiliansoelch** [comment]
#151 does not completely solve the Kubernetes issue, as we need to address the service instead of the container (e.g., `"http://module-example-service:5001"`).
In general, I think you could name the Kubernetes services to make it work, but I think this is not the best practice.

Further, I like the optional flexibility of overwriting the default module URLs.

**Review by FelixTJDietrich — APPROVED** [review]
Alright, in that case this seems fine to me 👍

**Comment by pal03377** [comment]
In this case, I also think that makes sense 👍

**Review by pal03377 — APPROVED** [review]

**Pull request merged**
