### PR TITLE
Update playground dependencies and remove unnecessary dependencies

### PR DESCRIPTION
**Pull request by FelixTJDietrich**
### Motivation and Context

Keep the dependencies up to date and clean.

### Description

- [x] Update all dependencies to the latest version
- [x] Fix dependencies to a fixed version (not using `^`)
- [x] Remove unnecessary dependencies

### Steps for Testing

- Test playground
- Test playground scripts 

closes #146
closes #148

### CODE REVIEW

**Comment by pal03377** [comment]
What's the difference between this PR and #148?

**Comment by pal03377** [comment]
Also closes #116

**Comment by FelixTJDietrich** [comment]
> What's the difference between this PR and #148?

As far as I can see two dependencies are more up to date (major versions). I also removed `"fs": "0.0.1-security"` which seems to be a mistake, removing it does not break the scripts etc. I also moved some dependencies around for example `axios` is a dev dependency now.

**Comment by FelixTJDietrich** [comment]
I tested everything on the test server and everything works as expected 👍 will merge it right away.

**Pull request merged**
